version: "3.7"
services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_PASSWORD=secretdocker
      - POSTGRES_USER=docker
      - POSTGRES_DB=mblabs
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - 5432:5432
  mblabs:
    container_name: mblabs
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: .env
    environment:
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USERNAME=${DB_USERNAME}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
    ports:
      - 3333:3333
    external_links:
      - postgres
    depends_on:
      - postgres
volumes:
  pgdata:
    driver: local